version: '3.9'

services:
  api:
    container_name: api
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    ports:
      - 2000:8080
    depends_on:
      - database
    restart: on-failure
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dbFastapi
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - database

